# Generated by Django 3.0.2 on 2020-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi', models.CharField(max_length=100)),
                ('researcher', models.CharField(max_length=100)),
            ],
        ),
    ]
