# Generated by Django 3.0.2 on 2020-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0002_cages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cages',
            name='cage_type',
            field=models.CharField(choices=[('S', 'STOCK'), ('B', 'BREEDING'), ('E', 'EXPERIMENTAL')], default='S', max_length=1),
        ),
    ]
