# Generated by Django 3.0.2 on 2020-03-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0003_cages_cage_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cages',
            new_name='Cage',
        ),
    ]
