# Generated by Django 3.0.2 on 2020-03-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0004_auto_20200304_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='ri',
            field=models.CharField(choices=[('Singapore Bioimaging Consortium', 'SBIC'), ('Bioprocessing Technology Institute', 'BTI')], default='Singapore Bioimaging Consortium', max_length=100),
        ),
        migrations.AlterField(
            model_name='cage',
            name='pi',
            field=models.CharField(choices=[('TOMMY TAN', 'TOMMY TAN'), ('LIM XIU XIU', 'LIM XIU XIU')], default='TOMMY TAN', max_length=100),
        ),
    ]
