# Generated by Django 3.0.2 on 2020-03-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0005_auto_20200305_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='facility',
            field=models.CharField(choices=[('Department 1', 'D1'), ('Department 2', 'D2')], default='Department 1', max_length=20),
        ),
    ]
