# Generated by Django 3.0.2 on 2020-03-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0006_cage_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='column',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='cage',
            name='rack',
            field=models.CharField(choices=[('RACK 1', 'RACK 1'), ('RACK 2', 'RACK 2'), ('RACK 3', 'RACK 3'), ('RACK 4', 'RACK 4'), ('RACK 5', 'RACK 5')], default='RACK 1', max_length=20),
        ),
        migrations.AddField(
            model_name='cage',
            name='room',
            field=models.CharField(choices=[('ROOM 1', 'ROOM 1'), ('ROOM 2', 'ROOM 2'), ('ROOM 3', 'ROOM 3'), ('ROOM 4', 'ROOM 4'), ('ROOM 5', 'ROOM 5')], default='Department 1', max_length=20),
        ),
        migrations.AddField(
            model_name='cage',
            name='row',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=20),
        ),
    ]
