# Generated by Django 3.0.2 on 2020-03-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0007_auto_20200305_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('cage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rodents.Cage')),
            ],
        ),
    ]
