# Generated by Django 3.0.4 on 2020-03-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodents', '0008_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='cage_type',
            field=models.CharField(choices=[('Stock', 'STOCK'), ('Breeding', 'BREEDING'), ('Experimental', 'EXPERIMENTAL')], default='Stock', max_length=15),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
